name       : font-overpass-otf
version    : 3.0.4
release    : 3
source     :
    - https://github.com/RedHatBrand/Overpass/archive/3.0.4.tar.gz : 07600d6745f5199ad210c7f39e934dcd9716b54615e44ccf1f830001a0da3597
license    :
    - OFL-1.1
    - LGPL-2.1-or-later
component  : desktop.font
summary    : Overpass font family
description: |
    An open source font family inspired by Highway Gothic.
install    : |
    install -dm00755 $installdir/usr/share/fonts/opentype/overpass{,-mono}
    install -m00644 desktop-fonts/overpass/*.otf $installdir/usr/share/fonts/opentype/overpass/.
    install -m00644 desktop-fonts/overpass-mono/*.otf $installdir/usr/share/fonts/opentype/overpass-mono/.
