name       : font-overpass-otf
version    : 3.0.2
release    : 1
source     :
    - https://github.com/RedHatBrand/Overpass/releases/download/3.0.2/overpass-desktop-fonts.zip : 10d2186ad1e1e628122f2e4ea0bbde16438e34a0068c35190d41626d89bb64e4 
license    : 
    - OFL-1.1
    - LGPL-2.1
component  : desktop.font
summary    : Overpass font family
description: |
    An open source font family inspired by Highway Gothic.
install    : |
    cd ..
    install -D -d -m 00755 $installdir/usr/share/fonts/opentype/overpass{,-mono}
    install -m 00644 overpass/*.otf $installdir/usr/share/fonts/opentype/overpass/.
    install -m 00644 overpass-mono/*.otf $installdir/usr/share/fonts/opentype/overpass-mono/.
