name       : font-overpass-otf
version    : 3.0.3
release    : 2
source     :
    - https://github.com/RedHatBrand/Overpass/archive/3.0.3.tar.gz : 5575965097b1682330a9a4d36e4090bfe53f6cf97f72351adbf44e05e008a8aa
license    :
    - OFL-1.1
    - LGPL-2.1
component  : desktop.font
summary    : Overpass font family
description: |
    An open source font family inspired by Highway Gothic.
install    : |
    install -D -d -m 00755 $installdir/usr/share/fonts/opentype/overpass{,-mono}
    install -m 00644 desktop-fonts/overpass/*.otf $installdir/usr/share/fonts/opentype/overpass/.
    install -m 00644 desktop-fonts/overpass-mono/*.otf $installdir/usr/share/fonts/opentype/overpass-mono/.
